services:
  db:
    image: postgres:13-alpine
    container_name: desafio_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env # Carrega as variáveis de ambiente do arquivo .env
    ports:
      - "5432:5432" # Opcional: para conectar ao banco de dados da sua máquina
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: desafio_backend
    volumes:
      # Renomeie SEU arquivo CSV para o nome abaixo na pasta data
      - ./backend/dados/Series_02_07_2025_13_30_29.csv:/code/data/Series_02_07_2025_13_30_29.csv
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Espera o banco de dados estar saudável

  frontend:
    build: ./frontend
    container_name: desafio_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: